### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by FredericaBernkastel** [mserajnik/mserajnik#2]
Hey, don't you think it's unfair from your side deleting all the code?
Let me update hydrusrv to 8.0 on my instance, and do everything you want.

**Comment by mserajnik** [comment]
I didn’t delete anything, but the projects are private for a reason now (the reason not being that I work on something new; in fact, that is also on ice for now).

I won‘t go into details because GitHub is not the platform to talk about this and frankly, it‘s of nobodies concern.

**Comment by mserajnik** [comment]
The code will be public again later this day.

**Comment by mserajnik** [comment]
Ping.
